---
###############################################################################
# NPM APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'npm-pipeline.yml'
    ref: 'v1.3.0'

variables:
  CUSTOMER: 'coghent'
  APPLICATION: 'coghent-bff'
  TERRAFORM_IMAGE: 'web-terraform'
  TERRAFORM_TAG: 'latest'
